version: "3"
services:
  opencv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      # binds everything in the root dir to the src dir in the container
      - ./:/src
      # used for vscode settings persistant data
      - vscodeServerData:/.vscod-server

# this will keep and vscode server data
# i.e. extentions installed when turning off the container
# this information is saved on the host machine in the docker system files
volumes:
  vscodeServerData:
